markdown: redcarpet2
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables",     "with_toc_data"]
twitter: cornae
title: Cornae
author: Cornelis G. A. Kolbach
baseurl: /cornae