markdown: rdiscount
pygments: true
permalink: /posts/:title
auto: true
rdiscount:
  extensions: [smart]
gravatar: 123
url: http://localhost:4000
feedburner: christophehamerling
ga: UA-25231338-1
disqus: christophehamerling
twitter: chamerling
title: Title
subtitle: Subtitle
author: My Name
