title: Cornae
author: Cornelis G. A. Kolbach
gems: ["jekyll-paginate"]
baseurl: 'http://www.cornae.com'
domain: cornae.com
media: /media
permalink: /:title
paginate: 3
encoding: utf-8
exclude: ['bungledeps']
sass:
  style: compressed
categories:
- articles
- cases
tags:
- article
- case