title: Cornae
author: Cornelis Kolbach
baseurl: '/'
domain: cornae.com
media: /media
permalink: /:title
paginate: 5
encoding: utf-8
exclude: ['bungledeps']
sass:
  style: compressed
categories:
- articles
- cases
tags:
- article
- case